# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'messenger.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_QuestMessenger(object):
    def setupUi(self, QuestMessenger):
        QuestMessenger.setObjectName("QuestMessenger")
        QuestMessenger.resize(1993, 1088)
        self.centralwidget = QtWidgets.QWidget(QuestMessenger)
        self.centralwidget.setObjectName("centralwidget")
        self.NodeFrame = NodeFrameClass(self.centralwidget)
        self.NodeFrame.setGeometry(QtCore.QRect(0, 0, 1511, 941))
        self.NodeFrame.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.NodeFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.NodeFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.NodeFrame.setObjectName("NodeFrame")
        self.label = QtWidgets.QLabel(self.NodeFrame)
        self.label.setGeometry(QtCore.QRect(10, 10, 83, 19))
        self.label.setObjectName("label")
        self.MessagesArea = QtWidgets.QScrollArea(self.NodeFrame)
        self.MessagesArea.setGeometry(QtCore.QRect(10, 80, 701, 761))
        self.MessagesArea.setWidgetResizable(True)
        self.MessagesArea.setObjectName("MessagesArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 699, 759))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.MessagesArea.setWidget(self.scrollAreaWidgetContents)
        self.SendBar = QtWidgets.QFrame(self.NodeFrame)
        self.SendBar.setGeometry(QtCore.QRect(10, 840, 1491, 61))
        self.SendBar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.SendBar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.SendBar.setObjectName("SendBar")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.SendBar)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.send_message = QtWidgets.QLineEdit(self.SendBar)
        self.send_message.setMinimumSize(QtCore.QSize(1300, 30))
        self.send_message.setMaximumSize(QtCore.QSize(1300, 30))
        self.send_message.setObjectName("send_message")
        self.horizontalLayout_2.addWidget(self.send_message)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.pushButton_2 = QtWidgets.QPushButton(self.SendBar)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_2.addWidget(self.pushButton_2)
        self.EncryptedSentArea = QtWidgets.QScrollArea(self.NodeFrame)
        self.EncryptedSentArea.setGeometry(QtCore.QRect(710, 80, 391, 761))
        self.EncryptedSentArea.setWidgetResizable(True)
        self.EncryptedSentArea.setObjectName("EncryptedSentArea")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 389, 759))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.EncryptedSentArea.setWidget(self.scrollAreaWidgetContents_2)
        self.EncryptedReceivedArea = QtWidgets.QScrollArea(self.NodeFrame)
        self.EncryptedReceivedArea.setGeometry(QtCore.QRect(1100, 80, 391, 761))
        self.EncryptedReceivedArea.setWidgetResizable(True)
        self.EncryptedReceivedArea.setObjectName("EncryptedReceivedArea")
        self.scrollAreaWidgetContents_3 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 389, 759))
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.EncryptedReceivedArea.setWidget(self.scrollAreaWidgetContents_3)
        self.MessageLabel = QtWidgets.QLabel(self.NodeFrame)
        self.MessageLabel.setGeometry(QtCore.QRect(16, 50, 691, 31))
        self.MessageLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.MessageLabel.setObjectName("MessageLabel")
        self.EncrypSentLabel = QtWidgets.QLabel(self.NodeFrame)
        self.EncrypSentLabel.setGeometry(QtCore.QRect(716, 49, 381, 31))
        self.EncrypSentLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.EncrypSentLabel.setObjectName("EncrypSentLabel")
        self.EncryptReceivedLabel = QtWidgets.QLabel(self.NodeFrame)
        self.EncryptReceivedLabel.setGeometry(QtCore.QRect(1100, 50, 381, 31))
        self.EncryptReceivedLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.EncryptReceivedLabel.setObjectName("EncryptReceivedLabel")
        self.NodeListFrame = QtWidgets.QFrame(self.centralwidget)
        self.NodeListFrame.setGeometry(QtCore.QRect(1520, 10, 361, 931))
        self.NodeListFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.NodeListFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.NodeListFrame.setObjectName("NodeListFrame")
        self.listWidget = QtWidgets.QListWidget(self.NodeListFrame)
        self.listWidget.setGeometry(QtCore.QRect(5, 11, 351, 921))
        self.listWidget.setObjectName("listWidget")
        self.ListNodesLabel = QtWidgets.QLabel(self.NodeListFrame)
        self.ListNodesLabel.setGeometry(QtCore.QRect(16, 22, 331, 51))
        self.ListNodesLabel.setObjectName("ListNodesLabel")
        self.OpenNodeButton = QtWidgets.QPushButton(self.NodeListFrame)
        self.OpenNodeButton.setGeometry(QtCore.QRect(14, 82, 341, 51))
        self.OpenNodeButton.setObjectName("OpenNodeButton")
        QuestMessenger.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(QuestMessenger)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1993, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        QuestMessenger.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(QuestMessenger)
        self.statusbar.setObjectName("statusbar")
        QuestMessenger.setStatusBar(self.statusbar)
        self.actionExit = QtWidgets.QAction(QuestMessenger)
        self.actionExit.setObjectName("actionExit")
        self.actionAbout = QtWidgets.QAction(QuestMessenger)
        self.actionAbout.setObjectName("actionAbout")
        self.menuFile.addAction(self.actionAbout)
        self.menuFile.addAction(self.actionExit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(QuestMessenger)
        QtCore.QMetaObject.connectSlotsByName(QuestMessenger)

    def retranslateUi(self, QuestMessenger):
        _translate = QtCore.QCoreApplication.translate
        QuestMessenger.setWindowTitle(_translate("QuestMessenger", "MainWindow"))
        self.label.setText(_translate("QuestMessenger", "Node Name"))
        self.pushButton_2.setText(_translate("QuestMessenger", "Send"))
        self.MessageLabel.setText(_translate("QuestMessenger", "Messages"))
        self.EncrypSentLabel.setText(_translate("QuestMessenger", "Encrypted Sent Messages"))
        self.EncryptReceivedLabel.setText(_translate("QuestMessenger", "Encrypted Received Messages"))
        self.ListNodesLabel.setText(_translate("QuestMessenger", "Online Nodes"))
        self.OpenNodeButton.setText(_translate("QuestMessenger", "Self"))
        self.menuFile.setTitle(_translate("QuestMessenger", "File"))
        self.actionExit.setText(_translate("QuestMessenger", "Exit"))
        self.actionAbout.setText(_translate("QuestMessenger", "About"))

from nodeframeclass import NodeFrameClass
